name: OBS Studio Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        PREVIOUSLTS=$(wget -q https://releases.ubuntu.com/ -O - | grep class | grep LTS | grep -m2 href | tail -n1 | sed -n 's/.*href="\([^"]*\).*/\1/p' | rev| cut -c 2- | rev)
        DEB=$(wget -q https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu/pool/main/o/obs-studio/ -O - | grep $PREVIOUSLTS | grep amd64.deb | grep -o -P '(?<=href=").*(?=">obs)')
        wget https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu/pool/main/o/obs-studio/$DEB
        sudo dpkg -i *.deb
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt
        chmod a+x ./linuxdeployqt
        APP=obs-studio
        version=$(wget -q https://api.github.com/repos/obsproject/obs-studio/releases/latest -O - | grep tag_name | cut -d '"' -f 4 | head -1)
        mkdir $APP.AppDir $APP.AppDir/usr $APP.AppDir/usr/bin $APP.AppDir/lib $APP.AppDir/usr/lib $APP.AppDir/usr/lib $APP.AppDir/usr/share $APP.AppDir/usr/share/applications $APP.AppDir/usr/share/icons $APP.AppDir/usr/share/icons/hicolor $APP.AppDir/usr/share/icons/hicolor/128x128 $APP.AppDir/usr/share/icons/hicolor/256x256 $APP.AppDir/usr/share/icons/hicolor/128x128/apps $APP.AppDir/usr/share/icons/hicolor/256x256/apps
        cp /usr/share/applications/*obs*desktop $APP.AppDir/usr/share/applications/$APP.desktop
        cp /usr/share/icons/hicolor/128x128/apps/*obs* $APP.AppDir/usr/share/icons/hicolor/128x128/apps/
        cp /usr/share/icons/hicolor/256x256/apps/*obs* $APP.AppDir/usr/share/icons/hicolor/256x256/apps/
        ./linuxdeployqt $APP.AppDir/usr/share/applications/$APP.desktop -appimage -bundle-non-qt-libs
        mkdir dist
        mv *AppImage dist/$APP-$version-x86_64.AppImage

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: OBS-Studio-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: OBS-Studio-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: true
            draft: false
            files: |
              OBS-Studio-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
