name: OBS Studio Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo add-apt-repository ppa:obsproject/obs-studio && sudo apt-get update && sudo apt-get install obs-studio
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt
        chmod a+x ./linuxdeployqt
        APP=obs-studio
        version=$(wget -q https://api.github.com/repos/obsproject/obs-studio/releases/latest -O - | grep tag_name | cut -d '"' -f 4 | head -1)
        mkdir -p $APP.AppDir $APP.AppDir/usr $APP.AppDir/usr/bin $APP.AppDir/lib $APP.AppDir/usr/lib $APP.AppDir/usr/lib $APP.AppDir/usr/share $APP.AppDir/usr/share/applications $APP.AppDir/usr/share/icons $APP.AppDir/usr/share/icons/hicolor $APP.AppDir/usr/share/icons/hicolor/128x128 $APP.AppDir/usr/share/icons/hicolor/256x256 $APP.AppDir/usr/share/icons/hicolor/128x128/apps $APP.AppDir/usr/share/icons/hicolor/256x256/apps
        cp /usr/bin/obs $APP.AppDir/usr/bin/
        cp /usr/share/applications/com.obsproject.Studio.desktop $APP.AppDir/usr/share/applications/
        cp /usr/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png $APP.AppDir/usr/share/icons/hicolor/128x128/apps/
        cp /usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png $APP.AppDir/usr/share/icons/hicolor/256x256/apps/
        cp /usr/share/icons/hicolor/512x512/apps/com.obsproject.Studio.png $APP.AppDir/usr/share/icons/hicolor/256x256/apps/
        ./linuxdeployqt $APP.AppDir/usr/share/applications/com.obsproject.Studio.desktop -appimage -bundle-non-qt-libs
        mkdir dist
        mv *AppImage dist/$APP-$version-x86_64.AppImage

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: OBS-Studio-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: OBS-Studio-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: true
            draft: false
            files: |
              OBS-Studio-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
