name: OBS Studio Portable
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        ls -a

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: OBS-Studio-x86_64.Portable
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: OBS-Studio-x86_64.Portable

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous Portable
            automatic_release_tag: continuous-portable
            prerelease: true
            draft: false
            files: |
              OBS-Studio-x86_64.Portable
            repo_token: ${{ secrets.GITHUB_TOKEN }}
